In [51]:
import pandas as pd

In [52]:
# Load data
df = pd.read_csv('BenettonSuppliers.csv')

## Product types

In [53]:
# Replace the values in the column 'APPAREL', 'ACCESSORIES' and 'SHOES' with True if the content is l 
# False if the entire content of the cell is empty


df['APPAREL'] = df['APPAREL'].replace('l', True)
df['APPAREL'] = df['APPAREL'].fillna(False)
df['ACCESSORIES'] = df['ACCESSORIES'].replace('l', True)
df['ACCESSORIES'] = df['ACCESSORIES'].fillna(False)
df['SHOES'] = df['SHOES'].replace('l', True)
df['SHOES'] = df['SHOES'].fillna(False)

# render the table in a browsable way

from IPython.display import display
display(df)

,COUNTRY,VENDOR,COMPANY NAME,ADDRESS,APPAREL,ACCESSORIES,SHOES,PRODUCTION PHASE,EMPLOYEES RANGE,% MEN,% WOMEN,% MIGRANT WORKERS,TRADE UNION,NAME OF THE TRADE UNION,COLLECTIVE BARGAINING AGREEMENT,% WORKFORCE COVERED BY THE CBA,WORKERS' REPRESENTATIVES,CERTIFICATIONS
0,TURKEY,Global Sourcing Dis Tic A.S,4P Empirme San. Ve Tic.Ltd.Sti.,"Mimar Sinan Cd No:9, Baglar Mahallesi, Bagcila...",True,False,False,PRINTING,1-500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,INDIA,C.R.Garments,A To Z Cotton Centre,"Miller Bus Stop, 414, Pn Rd, Vengamedu, Poyamp...",True,False,False,WEAVING,1-500,70.0,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,INDIA,Shahi Exports Pvt Ltd.,Aarti International Limited,"Vill. Bhama Kalan & Harhian , P . O . Uppal , ...",True,False,False,WET PROCESS; WEAVING,501-1500,97.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,TURKEY,Aba Tekstil Orme San Ve Tic As,Aba Tekstil Orme San Ve Tic A.S.,Merkez Mah. Prof Dr Nevzat Pisak Cad. No19 Yen...,True,False,False,SPINNING; WEAVING,1-500,50.0,50.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,CHINA,Demka Tekstil San Ve Tic As,"Ac International Co., Ltd","Room 1330, Yuemin Building, 114 Xingang West R...",True,False,False,WEAVING,1-500,100.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
736,CHINA,Talisman Ltd,Zhejiang Yingfeng Technology Co .Ltd,Binhai Industrial Park (At The Cross Of North ...,True,False,False,WET PROCESS,501-1500,90.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
737,CHINA,"Win-Light Textile Co.,Ltd","Zhejiang Win-Light Apparel Co.,Ltd","Industry Area, Deqing; Huzhou; 313000 (Zhejiang)",True,False,False,MANUFACTURING,1-500,60.0,40.0,23.0,l,win-light union committee,l,100.0,l,NaN
738,CHINA,South Ocean Knitters Limited,Zhuhai Anderson Garment Company Limited,"No. 241 Jinfa Road, Guantang Hi Tech Zone, Tan...",True,False,False,MANUFACTURING,1-500,38.0,62.0,0.0,NaN,NaN,NaN,NaN,NaN,BSCI
739,CHINA,Sunhong Global Investment Limited,"Zhuji Mingrun Textile Garments Co.,Ltd.","No.12 Li Kai Road, Jiyang Street; Shaoxing Cit...",True,False,False,MANUFACTURING; OTHER PROCESSING,1-500,36.0,64.0,19.0,NaN,NaN,NaN,NaN,l,BSCI
740,CHINA,"Quanzhou Skysun Science And Technology Co., Ltd.","Zhuji Shengmai Shoes Co., Ltd.","No. 16, Jihui Road, Zhibu Town; Zhuji City; 31...",False,False,True,MANUFACTURING,1-500,55.0,45.0,0.0,NaN,NaN,NaN,NaN,l,BSCI

## Geographical location

In [54]:
# Show me the entire content of the ADDRESS column of 10 rows
df['ADDRESS'][700]

# This tells me that I can split the column by the ; and that there are 3 main elements.
# I can then split the column by the ; and create a column for the street, one for the city and one for the county/postcode

'Beside Taipe River Meiyan Community Pingwang Town Wujiang District; Suzhou; 215200 (Jiangsu)'

In [55]:
# I am checking for how many ; there are in the column ADDRESS

df['ADDRESS'].str.count(';').value_counts()

ADDRESS
2    741
Name: count, dtype: int64

In [56]:
# I see some irregularity with the number of ; in the column ADDRESS. 
# I am checking the rows where there are 3 ; and I remove them by hand using libreoffice calc

df[df['ADDRESS'].str.count(';') == 3]

Empty DataFrame
Columns: [COUNTRY, VENDOR, COMPANY NAME, ADDRESS, APPAREL, ACCESSORIES, SHOES, PRODUCTION PHASE, EMPLOYEES RANGE, % MEN, % WOMEN, % MIGRANT WORKERS, TRADE UNION, NAME OF THE TRADE UNION, COLLECTIVE BARGAINING AGREEMENT, % WORKFORCE COVERED BY THE CBA, WORKERS' REPRESENTATIVES, CERTIFICATIONS]
Index: []

In [57]:
# Same thing for the number of ; = 1
df[df['ADDRESS'].str.count(';') == 1]

Empty DataFrame
Columns: [COUNTRY, VENDOR, COMPANY NAME, ADDRESS, APPAREL, ACCESSORIES, SHOES, PRODUCTION PHASE, EMPLOYEES RANGE, % MEN, % WOMEN, % MIGRANT WORKERS, TRADE UNION, NAME OF THE TRADE UNION, COLLECTIVE BARGAINING AGREEMENT, % WORKFORCE COVERED BY THE CBA, WORKERS' REPRESENTATIVES, CERTIFICATIONS]
Index: []

In [58]:
# I fixed the irregularities in libreoffice calc and I run again the notebook to load the new csv file.
# Split the 'ADDRESS' column into 'STREET', 'CITY' and 'ZIP' columns based on the ; separator, except 
# for the rows that have 1 or 3 ; in the column 'ADDRESS'

df['STREET'] = df['ADDRESS'].str.split(';').str[0]
df['CITY'] = df['ADDRESS'].str.split(';').str[1]
df['ZIP'] = df['ADDRESS'].str.split(';').str[2]

In [59]:
# Split the column 'ADDRESS' into 'ADDRESS' and 'COUNTY', by extracting the words in brackets and putting them in a new column. Remove the brackets and the words in them from the 'ADDRESS' column.
df['COUNTY'] = df['ADDRESS'].str.extract(r'\((.*?)\)')
df['ADDRESS'] = df['ADDRESS'].str.replace(r'\(.*?\)','')
df.head()

,COUNTRY,VENDOR,COMPANY NAME,ADDRESS,APPAREL,ACCESSORIES,SHOES,PRODUCTION PHASE,EMPLOYEES RANGE,% MEN,% WOMEN,% MIGRANT WORKERS,TRADE UNION,NAME OF THE TRADE UNION,COLLECTIVE BARGAINING AGREEMENT,% WORKFORCE COVERED BY THE CBA,WORKERS' REPRESENTATIVES,CERTIFICATIONS,STREET,CITY,ZIP,COUNTY
0,TURKEY,Global Sourcing Dis Tic A.S,4P Empirme San. Ve Tic.Ltd.Sti.,"Mimar Sinan Cd No:9, Baglar Mahallesi, Bagcila...",True,False,False,PRINTING,1-500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Mimar Sinan Cd No:9, Baglar Mahallesi, Bagcilar",Istanbul,34209 (Istanbul),Istanbul
1,INDIA,C.R.Garments,A To Z Cotton Centre,"Miller Bus Stop, 414, Pn Rd, Vengamedu, Poyamp...",True,False,False,WEAVING,1-500,70.0,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Miller Bus Stop, 414, Pn Rd, Vengamedu, Poyamp...",Tirupur,641602 (Tamil Nadu),Tamil Nadu
2,INDIA,Shahi Exports Pvt Ltd.,Aarti International Limited,"Vill. Bhama Kalan & Harhian , P . O . Uppal , ...",True,False,False,WET PROCESS; WEAVING,501-1500,97.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Vill. Bhama Kalan & Harhian , P . O . Uppal , ...",Ludhiana,141113 (Punjab),Punjab
3,TURKEY,Aba Tekstil Orme San Ve Tic As,Aba Tekstil Orme San Ve Tic A.S.,Merkez Mah. Prof Dr Nevzat Pisak Cad. No19 Yen...,True,False,False,SPINNING; WEAVING,1-500,50.0,50.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Merkez Mah. Prof Dr Nevzat Pisak Cad. No19 Yen...,Instanbul,34180 (Istanbul),Istanbul
4,CHINA,Demka Tekstil San Ve Tic As,"Ac International Co., Ltd","Room 1330, Yuemin Building, 114 Xingang West R...",True,False,False,WEAVING,1-500,100.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Room 1330, Yuemin Building, 114 Xingang West R...",Guangzhou,510000 (Guangdong),Guangdong

In [60]:
# Print column names
df.columns

df = df[['COMPANY NAME',  'VENDOR', 'COUNTRY', 'COUNTY', 'ZIP', 'CITY', 'STREET', 'ADDRESS',  'APPAREL',
         'ACCESSORIES', 'SHOES', 'PRODUCTION PHASE', 'EMPLOYEES RANGE', '% MEN',
         '% WOMEN', '% MIGRANT WORKERS', 'TRADE UNION',
         'NAME OF THE TRADE UNION', 'COLLECTIVE BARGAINING AGREEMENT',
         '% WORKFORCE COVERED BY THE CBA', 'WORKERS\' REPRESENTATIVES',
         'CERTIFICATIONS']]

df.head()

,COMPANY NAME,COUNTRY,COUNTY,ZIP,CITY,STREET,ADDRESS,VENDOR,APPAREL,ACCESSORIES,SHOES,PRODUCTION PHASE,EMPLOYEES RANGE,% MEN,% WOMEN,% MIGRANT WORKERS,TRADE UNION,NAME OF THE TRADE UNION,COLLECTIVE BARGAINING AGREEMENT,% WORKFORCE COVERED BY THE CBA,WORKERS' REPRESENTATIVES,CERTIFICATIONS
0,4P Empirme San. Ve Tic.Ltd.Sti.,TURKEY,Istanbul,34209 (Istanbul),Istanbul,"Mimar Sinan Cd No:9, Baglar Mahallesi, Bagcilar","Mimar Sinan Cd No:9, Baglar Mahallesi, Bagcila...",Global Sourcing Dis Tic A.S,True,False,False,PRINTING,1-500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,A To Z Cotton Centre,INDIA,Tamil Nadu,641602 (Tamil Nadu),Tirupur,"Miller Bus Stop, 414, Pn Rd, Vengamedu, Poyamp...","Miller Bus Stop, 414, Pn Rd, Vengamedu, Poyamp...",C.R.Garments,True,False,False,WEAVING,1-500,70.0,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Aarti International Limited,INDIA,Punjab,141113 (Punjab),Ludhiana,"Vill. Bhama Kalan & Harhian , P . O . Uppal , ...","Vill. Bhama Kalan & Harhian , P . O . Uppal , ...",Shahi Exports Pvt Ltd.,True,False,False,WET PROCESS; WEAVING,501-1500,97.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Aba Tekstil Orme San Ve Tic A.S.,TURKEY,Istanbul,34180 (Istanbul),Instanbul,Merkez Mah. Prof Dr Nevzat Pisak Cad. No19 Yen...,Merkez Mah. Prof Dr Nevzat Pisak Cad. No19 Yen...,Aba Tekstil Orme San Ve Tic As,True,False,False,SPINNING; WEAVING,1-500,50.0,50.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"Ac International Co., Ltd",CHINA,Guangdong,510000 (Guangdong),Guangzhou,"Room 1330, Yuemin Building, 114 Xingang West R...","Room 1330, Yuemin Building, 114 Xingang West R...",Demka Tekstil San Ve Tic As,True,False,False,WEAVING,1-500,100.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [61]:
# From the ZIP column, extract the terms in brackets and put them in a new column called 'COUNTY'
df['COUNTY'] = df['ZIP'].str.extract(r'\((.*?)\)')

df['ZIP'] = df['ZIP'].str.replace(r'\(.*?\)', '', regex=True)
df.head()

,COMPANY NAME,COUNTRY,COUNTY,ZIP,CITY,STREET,ADDRESS,VENDOR,APPAREL,ACCESSORIES,SHOES,PRODUCTION PHASE,EMPLOYEES RANGE,% MEN,% WOMEN,% MIGRANT WORKERS,TRADE UNION,NAME OF THE TRADE UNION,COLLECTIVE BARGAINING AGREEMENT,% WORKFORCE COVERED BY THE CBA,WORKERS' REPRESENTATIVES,CERTIFICATIONS
0,4P Empirme San. Ve Tic.Ltd.Sti.,TURKEY,Istanbul,34209,Istanbul,"Mimar Sinan Cd No:9, Baglar Mahallesi, Bagcilar","Mimar Sinan Cd No:9, Baglar Mahallesi, Bagcila...",Global Sourcing Dis Tic A.S,True,False,False,PRINTING,1-500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,A To Z Cotton Centre,INDIA,Tamil Nadu,641602,Tirupur,"Miller Bus Stop, 414, Pn Rd, Vengamedu, Poyamp...","Miller Bus Stop, 414, Pn Rd, Vengamedu, Poyamp...",C.R.Garments,True,False,False,WEAVING,1-500,70.0,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Aarti International Limited,INDIA,Punjab,141113,Ludhiana,"Vill. Bhama Kalan & Harhian , P . O . Uppal , ...","Vill. Bhama Kalan & Harhian , P . O . Uppal , ...",Shahi Exports Pvt Ltd.,True,False,False,WET PROCESS; WEAVING,501-1500,97.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Aba Tekstil Orme San Ve Tic A.S.,TURKEY,Istanbul,34180,Instanbul,Merkez Mah. Prof Dr Nevzat Pisak Cad. No19 Yen...,Merkez Mah. Prof Dr Nevzat Pisak Cad. No19 Yen...,Aba Tekstil Orme San Ve Tic As,True,False,False,SPINNING; WEAVING,1-500,50.0,50.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"Ac International Co., Ltd",CHINA,Guangdong,510000,Guangzhou,"Room 1330, Yuemin Building, 114 Xingang West R...","Room 1330, Yuemin Building, 114 Xingang West R...",Demka Tekstil San Ve Tic As,True,False,False,WEAVING,1-500,100.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [62]:
# Remove the ADDRESS column
df = df.drop(['ADDRESS'], axis=1)
df.head()

,COMPANY NAME,COUNTRY,COUNTY,ZIP,CITY,STREET,VENDOR,APPAREL,ACCESSORIES,SHOES,PRODUCTION PHASE,EMPLOYEES RANGE,% MEN,% WOMEN,% MIGRANT WORKERS,TRADE UNION,NAME OF THE TRADE UNION,COLLECTIVE BARGAINING AGREEMENT,% WORKFORCE COVERED BY THE CBA,WORKERS' REPRESENTATIVES,CERTIFICATIONS
0,4P Empirme San. Ve Tic.Ltd.Sti.,TURKEY,Istanbul,34209,Istanbul,"Mimar Sinan Cd No:9, Baglar Mahallesi, Bagcilar",Global Sourcing Dis Tic A.S,True,False,False,PRINTING,1-500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,A To Z Cotton Centre,INDIA,Tamil Nadu,641602,Tirupur,"Miller Bus Stop, 414, Pn Rd, Vengamedu, Poyamp...",C.R.Garments,True,False,False,WEAVING,1-500,70.0,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Aarti International Limited,INDIA,Punjab,141113,Ludhiana,"Vill. Bhama Kalan & Harhian , P . O . Uppal , ...",Shahi Exports Pvt Ltd.,True,False,False,WET PROCESS; WEAVING,501-1500,97.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Aba Tekstil Orme San Ve Tic A.S.,TURKEY,Istanbul,34180,Instanbul,Merkez Mah. Prof Dr Nevzat Pisak Cad. No19 Yen...,Aba Tekstil Orme San Ve Tic As,True,False,False,SPINNING; WEAVING,1-500,50.0,50.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"Ac International Co., Ltd",CHINA,Guangdong,510000,Guangzhou,"Room 1330, Yuemin Building, 114 Xingang West R...",Demka Tekstil San Ve Tic As,True,False,False,WEAVING,1-500,100.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [63]:
# Save the cleaned data in a new csv file
df.to_csv('BenettonSuppliersCleaned.csv', index=False)

In [64]:
# Represent the dataset using the display function and showing all of the columns.
from IPython.display import display
pd.options.display.max_columns = None
display(df)

,COMPANY NAME,COUNTRY,COUNTY,ZIP,CITY,STREET,VENDOR,APPAREL,ACCESSORIES,SHOES,PRODUCTION PHASE,EMPLOYEES RANGE,% MEN,% WOMEN,% MIGRANT WORKERS,TRADE UNION,NAME OF THE TRADE UNION,COLLECTIVE BARGAINING AGREEMENT,% WORKFORCE COVERED BY THE CBA,WORKERS' REPRESENTATIVES,CERTIFICATIONS
0,4P Empirme San. Ve Tic.Ltd.Sti.,TURKEY,Istanbul,34209,Istanbul,"Mimar Sinan Cd No:9, Baglar Mahallesi, Bagcilar",Global Sourcing Dis Tic A.S,True,False,False,PRINTING,1-500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,A To Z Cotton Centre,INDIA,Tamil Nadu,641602,Tirupur,"Miller Bus Stop, 414, Pn Rd, Vengamedu, Poyamp...",C.R.Garments,True,False,False,WEAVING,1-500,70.0,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Aarti International Limited,INDIA,Punjab,141113,Ludhiana,"Vill. Bhama Kalan & Harhian , P . O . Uppal , ...",Shahi Exports Pvt Ltd.,True,False,False,WET PROCESS; WEAVING,501-1500,97.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Aba Tekstil Orme San Ve Tic A.S.,TURKEY,Istanbul,34180,Instanbul,Merkez Mah. Prof Dr Nevzat Pisak Cad. No19 Yen...,Aba Tekstil Orme San Ve Tic As,True,False,False,SPINNING; WEAVING,1-500,50.0,50.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"Ac International Co., Ltd",CHINA,Guangdong,510000,Guangzhou,"Room 1330, Yuemin Building, 114 Xingang West R...",Demka Tekstil San Ve Tic As,True,False,False,WEAVING,1-500,100.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
736,Zhejiang Yingfeng Technology Co .Ltd,CHINA,Zhejiang,312000,Shaoxing,Binhai Industrial Park (At The Cross Of North ...,Talisman Ltd,True,False,False,WET PROCESS,501-1500,90.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
737,"Zhejiang Win-Light Apparel Co.,Ltd",CHINA,Zhejiang,313000,Huzhou,"Industry Area, Deqing","Win-Light Textile Co.,Ltd",True,False,False,MANUFACTURING,1-500,60.0,40.0,23.0,l,win-light union committee,l,100.0,l,NaN
738,Zhuhai Anderson Garment Company Limited,CHINA,Guangdong,510900,Tangjiawan,"No. 241 Jinfa Road, Guantang Hi Tech Zone, Tan...",South Ocean Knitters Limited,True,False,False,MANUFACTURING,1-500,38.0,62.0,0.0,NaN,NaN,NaN,NaN,NaN,BSCI
739,"Zhuji Mingrun Textile Garments Co.,Ltd.",CHINA,Zhejiang,312000,Shaoxing City,"No.12 Li Kai Road, Jiyang Street",Sunhong Global Investment Limited,True,False,False,MANUFACTURING; OTHER PROCESSING,1-500,36.0,64.0,19.0,NaN,NaN,NaN,NaN,l,BSCI
740,"Zhuji Shengmai Shoes Co., Ltd.",CHINA,Zhejiang,311800,Zhuji City,"No. 16, Jihui Road, Zhibu Town","Quanzhou Skysun Science And Technology Co., Ltd.",False,False,True,MANUFACTURING,1-500,55.0,45.0,0.0,NaN,NaN,NaN,NaN,l,BSCI

## Production phase

In [35]:
# split a column 'PRODUCTION PHASE' based on the ;. expand the row and keep each of the PRODUCTION PHASE in a new row
df_long = df
exploded = df_long['PRODUCTION PHASE'].str.split(';', n=8).explode()

In [36]:
# Use the exploded variable to create a new dataframe in which the PRODUCTION PHASE column is exploded

df_exploded = pd.DataFrame(exploded)
df_exploded.head()

  PRODUCTION PHASE
0         PRINTING
1          WEAVING
2      WET PROCESS
2          WEAVING
3         SPINNING

In [37]:
# Merge the two dataframes on the index
df_merged = df.merge(df_exploded, left_index=True, right_index=True)

In [38]:
df_merged = df_merged.drop(['PRODUCTION PHASE_x'], axis=1)
df_merged = df_merged.rename(columns={'PRODUCTION PHASE_y': 'PRODUCTION PHASE'})
df_merged.head()

df = df_merged

,COUNTRY,COUNTY,ZIP,CITY,STREET,VENDOR,COMPANY NAME,APPAREL,ACCESSORIES,SHOES,EMPLOYEES RANGE,% MEN,% WOMEN,% MIGRANT WORKERS,TRADE UNION,NAME OF THE TRADE UNION,COLLECTIVE BARGAINING AGREEMENT,% WORKFORCE COVERED BY THE CBA,WORKERS' REPRESENTATIVES,CERTIFICATIONS,PRODUCTION PHASE,PRODUCT
0,TURKEY,Istanbul,34209,Istanbul,"Mimar Sinan Cd No:9, Baglar Mahallesi, Bagcilar",Global Sourcing Dis Tic A.S,4P Empirme San. Ve Tic.Ltd.Sti.,True,False,False,1-500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PRINTING,APPAREL
1,INDIA,Tamil Nadu,641602,Tirupur,"Miller Bus Stop, 414, Pn Rd, Vengamedu, Poyamp...",C.R.Garments,A To Z Cotton Centre,True,False,False,1-500,70.0,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WEAVING,APPAREL
2,INDIA,Punjab,141113,Ludhiana,"Vill. Bhama Kalan & Harhian , P . O . Uppal , ...",Shahi Exports Pvt Ltd.,Aarti International Limited,True,False,False,501-1500,97.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WET PROCESS,APPAREL
2,INDIA,Punjab,141113,Ludhiana,"Vill. Bhama Kalan & Harhian , P . O . Uppal , ...",Shahi Exports Pvt Ltd.,Aarti International Limited,True,False,False,501-1500,97.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WEAVING,APPAREL
3,TURKEY,Istanbul,34180,Instanbul,Merkez Mah. Prof Dr Nevzat Pisak Cad. No19 Yen...,Aba Tekstil Orme San Ve Tic As,Aba Tekstil Orme San Ve Tic A.S.,True,False,False,1-500,50.0,50.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SPINNING,APPAREL

In [40]:
# Print column names
df.columns


df = df[['TRADE UNION',
         'NAME OF THE TRADE UNION', 'VENDOR',  'COMPANY NAME', 'APPAREL', 'SHOES', 'ACCESSORIES',
         'PRODUCTION PHASE', 'COUNTRY', 'COUNTY', 'ZIP', 'CITY', 'STREET', 
         'EMPLOYEES RANGE', '% MEN',
         '% WOMEN', '% MIGRANT WORKERS', 'COLLECTIVE BARGAINING AGREEMENT',
         '% WORKFORCE COVERED BY THE CBA', 'WORKERS\' REPRESENTATIVES',
         'CERTIFICATIONS']]

display(df)

,TRADE UNION,NAME OF THE TRADE UNION,VENDOR,COMPANY NAME,APPAREL,SHOES,ACCESSORIES,PRODUCTION PHASE,COUNTRY,COUNTY,ZIP,CITY,STREET,EMPLOYEES RANGE,% MEN,% WOMEN,% MIGRANT WORKERS,COLLECTIVE BARGAINING AGREEMENT,% WORKFORCE COVERED BY THE CBA,WORKERS' REPRESENTATIVES,CERTIFICATIONS
0,NaN,NaN,Global Sourcing Dis Tic A.S,4P Empirme San. Ve Tic.Ltd.Sti.,True,False,False,PRINTING,TURKEY,Istanbul,34209,Istanbul,"Mimar Sinan Cd No:9, Baglar Mahallesi, Bagcilar",1-500,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,C.R.Garments,A To Z Cotton Centre,True,False,False,WEAVING,INDIA,Tamil Nadu,641602,Tirupur,"Miller Bus Stop, 414, Pn Rd, Vengamedu, Poyamp...",1-500,70.0,30.0,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,Shahi Exports Pvt Ltd.,Aarti International Limited,True,False,False,WET PROCESS,INDIA,Punjab,141113,Ludhiana,"Vill. Bhama Kalan & Harhian , P . O . Uppal , ...",501-1500,97.0,3.0,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,Shahi Exports Pvt Ltd.,Aarti International Limited,True,False,False,WEAVING,INDIA,Punjab,141113,Ludhiana,"Vill. Bhama Kalan & Harhian , P . O . Uppal , ...",501-1500,97.0,3.0,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,Aba Tekstil Orme San Ve Tic As,Aba Tekstil Orme San Ve Tic A.S.,True,False,False,SPINNING,TURKEY,Istanbul,34180,Instanbul,Merkez Mah. Prof Dr Nevzat Pisak Cad. No19 Yen...,1-500,50.0,50.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
737,l,win-light union committee,"Win-Light Textile Co.,Ltd","Zhejiang Win-Light Apparel Co.,Ltd",True,False,False,MANUFACTURING,CHINA,Zhejiang,313000,Huzhou,"Industry Area, Deqing",1-500,60.0,40.0,23.0,l,100.0,l,NaN
738,NaN,NaN,South Ocean Knitters Limited,Zhuhai Anderson Garment Company Limited,True,False,False,MANUFACTURING,CHINA,Guangdong,510900,Tangjiawan,"No. 241 Jinfa Road, Guantang Hi Tech Zone, Tan...",1-500,38.0,62.0,0.0,NaN,NaN,NaN,BSCI
739,NaN,NaN,Sunhong Global Investment Limited,"Zhuji Mingrun Textile Garments Co.,Ltd.",True,False,False,MANUFACTURING,CHINA,Zhejiang,312000,Shaoxing City,"No.12 Li Kai Road, Jiyang Street",1-500,36.0,64.0,19.0,NaN,NaN,l,BSCI
739,NaN,NaN,Sunhong Global Investment Limited,"Zhuji Mingrun Textile Garments Co.,Ltd.",True,False,False,OTHER PROCESSING,CHINA,Zhejiang,312000,Shaoxing City,"No.12 Li Kai Road, Jiyang Street",1-500,36.0,64.0,19.0,NaN,NaN,l,BSCI
740,NaN,NaN,"Quanzhou Skysun Science And Technology Co., Ltd.","Zhuji Shengmai Shoes Co., Ltd.",False,True,False,MANUFACTURING,CHINA,Zhejiang,311800,Zhuji City,"No. 16, Jihui Road, Zhibu Town",1-500,55.0,45.0,0.0,NaN,NaN,l,BSCI

In [ ]:
# Replace the values in the column 'TRADE UNION' with True if the content is l
# False if the entire content of the cell is empty or NaN

df['TRADE UNION'] = df['TRADE UNION'].replace('l', True)
df['TRADE UNION'] = df['TRADE UNION'].fillna(False)


display(df)

In [ ]:
# How many cells are true in the column 'TRADE UNION'
df['TRADE UNION'].value_counts()

# trim the column 'NAME OF THE TRADE UNION' to remove the spaces at the beginning and at the end of the string
df['NAME OF THE TRADE UNION'] = df['NAME OF THE TRADE UNION'].str.strip()


# Count empty rows non-null in the 'NAME OF THE TRADE UNION' column
df.loc[df['TRADE UNION'] & df['NAME OF THE TRADE UNION'].isnull(), 'NAME OF THE TRADE UNION'] = 'Unknown'

In [ ]:
# Count false values in the 'TRADE UNION' column
false = df['TRADE UNION'].value_counts()[True]
false

In [ ]:
display(df)

In [ ]:
# They do not match. Ummh let's check visually:

df.to_csv('BenettonSuppliersCleaned3.0.csv', index=False)

In [ ]:
# Remove the column 'TRADE UNION'
# Rename the column 'NAME OF THE TRADE UNION' to 'TRADE UNION'
df.drop(['TRADE UNION'], axis=1, inplace=True)
df.rename(columns={'NAME OF THE TRADE UNION': 'TRADE UNION'}, inplace=True)

# Save the cleaned data in a new csv file
df.to_csv('BenettonSuppliersCleaned4.0.csv', index=False)

In [ ]:
df["CERTIFICATIONS"]

In [ ]:
# split a column 'CERTIFICATIONS' based on the ;. expand the row and keep each of the PRODUCTION PHASE in a new row
exploded = df['CERTIFICATIONS'].str.split(';', n=8).explode()

In [ ]:
# Use the exploded variable to create a new dataframe in which the PRODUCTION PHASE column is exploded

df_exploded = pd.DataFrame(exploded)
df_exploded.head()

In [ ]:
# Merge the two dataframes on the index
df_merged = df.merge(df_exploded, left_index=True, right_index=True)

In [ ]:
# Drop the column 'CERTIFICATIONS_x'
df_merged = df_merged.drop(['CERTIFICATIONS_x'], axis=1)
df_merged = df_merged.rename(columns={'CERTIFICATIONS_y': 'CERTIFICATIONS'})
df_merged.head()

In [ ]:
df_merged.head(50)

In [ ]:
# Merge the two dataframes on the index
df = df_merged

# Save the cleaned data in a new csv file
df.to_csv('BenettonSuppliersCleaned5.0.csv', index=False)

In [ ]:
# When the column 'WORKERS' REPRESENTATIVES' is equal to l, replace it with True, when it is 
df['WORKERS\' REPRESENTATIVES'] = df['WORKERS\' REPRESENTATIVES'].replace('l', True)
df['WORKERS\' REPRESENTATIVES'] = df['WORKERS\' REPRESENTATIVES'].fillna(False)

# Same thing for the column 'COLLECTIVE BARGAINING AGREEMENT'
df['COLLECTIVE BARGAINING AGREEMENT'] = df['COLLECTIVE BARGAINING AGREEMENT'].replace('l', True)
df['COLLECTIVE BARGAINING AGREEMENT'] = df['COLLECTIVE BARGAINING AGREEMENT'].fillna(False)



df.head()

In [ ]:
# Show me a summary of the column 'EMPLOYEES RANGE',
# and show me the number of unique values in the column 'EMPLOYEES RANGE'

df['EMPLOYEES RANGE'].describe()

df['EMPLOYEES RANGE'].unique()

In [ ]:
# How many rows have a nan value in the column 'EMPLOYEES RANGE'?
# Add another column 'MAX EMPLOYEES' that contains the maximum number of employees in the range

df['MAX EMPLOYEES'] = df['EMPLOYEES RANGE'].str.split('-').str[1]

In [ ]:

# Add another column 'MIN EMPLOYEES' that contains the minimum number of employees in the range
df['MIN EMPLOYEES'] = df['EMPLOYEES RANGE'].str.split('-').str[0]

# When the column 'EMPLOYEES RANGE' is equal to '5000',
# replace the value of the column 'MAX EMPLOYEES' with 5000
df.loc[df['EMPLOYEES RANGE'] == '>5000', 'MIN EMPLOYEES'] = 5000

In [ ]:
# Facet the column 'MAX EMPLOYEES', include the nan values
df['MAX EMPLOYEES'].value_counts(dropna=False)

In [ ]:
# Facet the column 'MIN EMPLOYEES', include the nan values
df['MIN EMPLOYEES'].value_counts(dropna=False)

In [ ]:
# Remove the column 'EMPLOYEES RANGE'
df.drop(['EMPLOYEES RANGE'], axis=1, inplace=True)

In [ ]:
df.head()

In [ ]:
# Print column names
df.columns

In [ ]:
df = df[['COMPANY NAME', 'VENDOR',  'PRODUCT', 'PRODUCTION PHASE',
       'COUNTRY', 'COUNTY', 'ZIP', 'CITY', 'STREET', 'MIN EMPLOYEES', 'MAX EMPLOYEES', 
       '% MEN', '% WOMEN','% MIGRANT WORKERS', 
       'TRADE UNION', 'COLLECTIVE BARGAINING AGREEMENT', '% WORKFORCE COVERED BY THE CBA', 
       "WORKERS' REPRESENTATIVES", 'CERTIFICATIONS']]

display(df)

In [ ]:
# Remove leading and trailing spaces from all the cells in the dataframe
df = df.apply(lambda x: x.str.strip() if x.dtype == "object" else x)

In [ ]:
# Save the cleaned data in a new csv file
df.to_csv('BenettonSuppliersCleaned6.0.csv', index=False)

In [ ]:
# Splitting the "PRODUCT" column based on the comma separator and creating binary columns for each category
product_categories = df['PRODUCT'].str.get_dummies(sep=',')

# Concatenating the new columns to the original DataFrame
df = pd.concat([df, product_categories], axis=1)

# Dropping the original "PRODUCT" column
df.drop(columns=['PRODUCT'], inplace=True)

# Displaying the first few rows of the transformed DataFrame
df.head()

In [ ]:
# Remove duplicates rows
df = df.drop_duplicates()

# Save the cleaned data in a new csv file
df.to_csv('BenettonSuppliersCleaned7.0.csv', index=False)

In [ ]:
# enumerate duplicate rows in the column 'COMPANY NAME', only if duplicate
df['DUPLICATE'] = df.duplicated(subset=['COMPANY NAME'], keep=False)

# If the column DUPLICATE is True, add a number to the column 'COMPANY NAME'
#df.loc[df['DUPLICATE'] == True, 'COMPANY NAME'] = df['COMPANY NAME'] + ' ' + df.groupby('COMPANY NAME').cumcount().add(1).astype(str)


df

In [ ]:
# Show me duplicate rows in the column 'COMPANY NAME'


# Replace the last character of the column 'COMPANY NAME' of duplicate rows with the number 3
df[df.duplicated(subset=['COMPANY NAME'], keep=False)]

In [ ]:
# Drop the column 'DUPLICATE'

df.drop(['DUPLICATE'], axis=1, inplace=True)

In [ ]:

# Save the cleaned data in a new csv file
df.to_csv('BenettonSuppliersCleaned8.0.csv', index=False)

In [ ]:
# How many rows are there in the dataframe?
df.shape[0]